countries = ["Canada", "France", "Belgium", "Ireland", "Italy"]
print(countries)
print(sorted(countries))
print(countries)
countries.sort(reverse = True)
print(countries)
countries.reverse()
print(countries)
countries.sort()
print(countries)
print(sorted(countries))
print(countries)
print(len(countries))
languages = ["English","Arabic","French","Swahili","Gujurati"]
print(languages)
print(languages[0])
print(languages[4])
languages.append("Chinese")
print(languages)
languages.insert(2,"Hindi")
languages.insert(3,"Spanish")
print(languages)
languages.append("Russian")
print(languages)
print(len(languages))
languages.pop(8)
print(languages)
languages.reverse()
print(languages)
print(sorted(languages))
print(languages)
languages.sort(reverse = True)
print(languages)
for language in languages:
    print(language.title() + ",is an international language.")
print("i really wish, i could learn all these languages in a month!")
animals = ["cows","camels","goats"]
for animal in animals:
    print(animal.title() + ", produce milk and have a body thats covered by fur.")
print("All these animals would make a great pet.")
for values in range(1,21):
    print(values)
numbers = list(range(1,1000000))
for numbers in range(1,1000000):
    print(numbers)
numbers = list(range(1,1000000))
print(min(numbers))
print(max(numbers))
print(sum(numbers))
odd_numbers = list(range(1,20,1))
for odd_numbres in range(1,20,1):
    print(odd_numbers)

